version: '3.7'

services:
  app:
    build: ./mo3jam
    restart: unless-stopped
    command: gunicorn -w 4 --bind 0.0.0.0:5000 'mo3jam:create_app()'
    volumes:
      - ./mo3jam:/app
    env_file:
      - ./.env.prod
    depends_on:
      - mo3jamdb
      - es01
    networks: 
      - backend
      - frontend
  
  mo3jamdb:
    image: mongo
    container_name: mo3jamdb
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_DATABASE: mo3jam
    networks: 
      - backend

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01data:/usr/share/elasticsearch/data
    networks:
      - backend

  webserver:
    build: ./nginx
    container_name: webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - app
    networks:
      - frontend
  
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  mongodata:
    driver: local
  es01data:
    driver: local
  nginxdata:
    driver: local