"""empty message

Revision ID: b7184cdad996
Revises: 
Create Date: 2019-09-17 13:46:44.195743

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'b7184cdad996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integer_sequenced_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('position', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index', 'integer_sequenced_items', ['sequence_id', 'position'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index', table_name='integer_sequenced_items')
    op.drop_table('integer_sequenced_items')
    # ### end Alembic commands ###
