# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mo3jam/grpc_services/search/search.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mo3jam/grpc_services/search/search.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(mo3jam/grpc_services/search/search.proto\"\x1c\n\x0bSearchQuery\x12\r\n\x05query\x18\x01 \x01(\t\"1\n\x0fSearchResultSet\x12\x1e\n\x07results\x18\x01 \x03(\x0b\x32\r.SearchResult\"\x1d\n\x0cSearchResult\x12\r\n\x05match\x18\x01 \x01(\t\"=\n\x15\x41utoCompleteResultSet\x12$\n\x07results\x18\x01 \x03(\x0b\x32\x13.AutoCompleteResult\"8\n\x12\x41utoCompleteResult\x12\r\n\x05match\x18\x01 \x01(\t\x12\x13\n\x0btranslation\x18\x02 \x01(\t2l\n\x06Search\x12*\n\x06search\x12\x0c.SearchQuery\x1a\x10.SearchResultSet\"\x00\x12\x36\n\x0c\x61utocomplete\x12\x0c.SearchQuery\x1a\x16.AutoCompleteResultSet\"\x00\x62\x06proto3')
)




_SEARCHQUERY = _descriptor.Descriptor(
  name='SearchQuery',
  full_name='SearchQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='SearchQuery.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=72,
)


_SEARCHRESULTSET = _descriptor.Descriptor(
  name='SearchResultSet',
  full_name='SearchResultSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='SearchResultSet.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=123,
)


_SEARCHRESULT = _descriptor.Descriptor(
  name='SearchResult',
  full_name='SearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='match', full_name='SearchResult.match', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=154,
)


_AUTOCOMPLETERESULTSET = _descriptor.Descriptor(
  name='AutoCompleteResultSet',
  full_name='AutoCompleteResultSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='AutoCompleteResultSet.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=217,
)


_AUTOCOMPLETERESULT = _descriptor.Descriptor(
  name='AutoCompleteResult',
  full_name='AutoCompleteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='match', full_name='AutoCompleteResult.match', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translation', full_name='AutoCompleteResult.translation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=275,
)

_SEARCHRESULTSET.fields_by_name['results'].message_type = _SEARCHRESULT
_AUTOCOMPLETERESULTSET.fields_by_name['results'].message_type = _AUTOCOMPLETERESULT
DESCRIPTOR.message_types_by_name['SearchQuery'] = _SEARCHQUERY
DESCRIPTOR.message_types_by_name['SearchResultSet'] = _SEARCHRESULTSET
DESCRIPTOR.message_types_by_name['SearchResult'] = _SEARCHRESULT
DESCRIPTOR.message_types_by_name['AutoCompleteResultSet'] = _AUTOCOMPLETERESULTSET
DESCRIPTOR.message_types_by_name['AutoCompleteResult'] = _AUTOCOMPLETERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchQuery = _reflection.GeneratedProtocolMessageType('SearchQuery', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHQUERY,
  '__module__' : 'mo3jam.grpc_services.search.search_pb2'
  # @@protoc_insertion_point(class_scope:SearchQuery)
  })
_sym_db.RegisterMessage(SearchQuery)

SearchResultSet = _reflection.GeneratedProtocolMessageType('SearchResultSet', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESULTSET,
  '__module__' : 'mo3jam.grpc_services.search.search_pb2'
  # @@protoc_insertion_point(class_scope:SearchResultSet)
  })
_sym_db.RegisterMessage(SearchResultSet)

SearchResult = _reflection.GeneratedProtocolMessageType('SearchResult', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESULT,
  '__module__' : 'mo3jam.grpc_services.search.search_pb2'
  # @@protoc_insertion_point(class_scope:SearchResult)
  })
_sym_db.RegisterMessage(SearchResult)

AutoCompleteResultSet = _reflection.GeneratedProtocolMessageType('AutoCompleteResultSet', (_message.Message,), {
  'DESCRIPTOR' : _AUTOCOMPLETERESULTSET,
  '__module__' : 'mo3jam.grpc_services.search.search_pb2'
  # @@protoc_insertion_point(class_scope:AutoCompleteResultSet)
  })
_sym_db.RegisterMessage(AutoCompleteResultSet)

AutoCompleteResult = _reflection.GeneratedProtocolMessageType('AutoCompleteResult', (_message.Message,), {
  'DESCRIPTOR' : _AUTOCOMPLETERESULT,
  '__module__' : 'mo3jam.grpc_services.search.search_pb2'
  # @@protoc_insertion_point(class_scope:AutoCompleteResult)
  })
_sym_db.RegisterMessage(AutoCompleteResult)



_SEARCH = _descriptor.ServiceDescriptor(
  name='Search',
  full_name='Search',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=277,
  serialized_end=385,
  methods=[
  _descriptor.MethodDescriptor(
    name='search',
    full_name='Search.search',
    index=0,
    containing_service=None,
    input_type=_SEARCHQUERY,
    output_type=_SEARCHRESULTSET,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='autocomplete',
    full_name='Search.autocomplete',
    index=1,
    containing_service=None,
    input_type=_SEARCHQUERY,
    output_type=_AUTOCOMPLETERESULTSET,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEARCH)

DESCRIPTOR.services_by_name['Search'] = _SEARCH

# @@protoc_insertion_point(module_scope)
